version: "3"
services:
  s3:
    image: "minio/minio:RELEASE.2021-08-31T05-46-54Z"
    hostname: "storage"
    restart: "no"
    volumes:
      - data:/data
    environment:
      - MINIO_ROOT_USER=s3accesskey
      - MINIO_ROOT_PASSWORD=s3secretkey
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: ["minio", "server", "/data","--console-address",":9001"]
    networks:
      - local
  backend:
    image: backend
    build:
      context: backend
    ports:
      - 8089:8089
    env_file:
      - ./backend/.env.docker
    healthcheck:
      test: [ "CMD", "curl", "-f" ,"http://localhost:8089/ready" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      - local
    depends_on:
      - s3
volumes:
  data:

networks:
  local: